/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.login;

import java.awt.Color;
import vista.register.Register;
import controlador.proxy.ProxyUsuario;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import vista.Dashboard;

/**
 *
 * @author Joel
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        PanelAzul = new javax.swing.JPanel();
        LDorado = new javax.swing.JLabel();
        LQAPT = new javax.swing.JLabel();
        LVuelos_Hoteles = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        PanelDorado = new javax.swing.JPanel();
        LAzul = new javax.swing.JLabel();
        Entrar = new javax.swing.JButton();
        TextPass = new javax.swing.JLabel();
        TextUser = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        Iuser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Ipass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelAzul.setBackground(new java.awt.Color(0, 0, 51));

        LDorado.setIcon(new javax.swing.ImageIcon("C:\\Users\\kevin\\Documents\\workspace\\patrones-de-disenio\\Hoteles_Vuelos\\src\\main\\java\\vista\\recursos\\images\\LogoDorado.png")); // NOI18N

        LQAPT.setIcon(new javax.swing.ImageIcon("C:\\Users\\kevin\\Documents\\workspace\\patrones-de-disenio\\Hoteles_Vuelos\\src\\main\\java\\vista\\recursos\\images\\LetrasQAPT.png")); // NOI18N

        LVuelos_Hoteles.setIcon(new javax.swing.ImageIcon("C:\\Users\\kevin\\Documents\\workspace\\patrones-de-disenio\\Hoteles_Vuelos\\src\\main\\java\\vista\\recursos\\images\\Letras_V_H.png")); // NOI18N

        btnRegistro.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistro.setFont(new java.awt.Font("Roboto Medium", 3, 28)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(255, 198, 0));
        btnRegistro.setText("Registro");
        btnRegistro.setBorder(null);
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelAzulLayout = new javax.swing.GroupLayout(PanelAzul);
        PanelAzul.setLayout(PanelAzulLayout);
        PanelAzulLayout.setHorizontalGroup(
            PanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAzulLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(PanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LQAPT, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelAzulLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(LVuelos_Hoteles, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
            .addGroup(PanelAzulLayout.createSequentialGroup()
                .addGroup(PanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAzulLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(LDorado, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAzulLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelAzulLayout.setVerticalGroup(
            PanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAzulLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(LDorado)
                .addGap(18, 18, 18)
                .addComponent(LQAPT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LVuelos_Hoteles, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        bg.add(PanelAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        PanelDorado.setBackground(new java.awt.Color(255, 198, 0));

        LAzul.setIcon(new javax.swing.ImageIcon("C:\\Users\\kevin\\Documents\\workspace\\patrones-de-disenio\\Hoteles_Vuelos\\src\\main\\java\\vista\\recursos\\images\\LogoAzul.png")); // NOI18N

        Entrar.setBackground(new java.awt.Color(0, 0, 0));
        Entrar.setFont(new java.awt.Font("Roboto Medium", 3, 28)); // NOI18N
        Entrar.setForeground(new java.awt.Color(255, 198, 0));
        Entrar.setText("Entrar");
        Entrar.setBorder(null);
        Entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntrarMouseClicked(evt);
            }
        });

        TextPass.setFont(new java.awt.Font("Roboto Black", 2, 15)); // NOI18N
        TextPass.setText("CONTRASEÑA");

        TextUser.setFont(new java.awt.Font("Roboto Black", 2, 15)); // NOI18N
        TextUser.setText("USUARIO");

        back.setBackground(new java.awt.Color(255, 198, 0));
        back.setFont(new java.awt.Font("Roboto Medium", 3, 28)); // NOI18N
        back.setForeground(new java.awt.Color(255, 198, 0));
        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\kevin\\Documents\\workspace\\patrones-de-disenio\\Hoteles_Vuelos\\src\\main\\java\\vista\\recursos\\images\\exit.png")); // NOI18N
        back.setBorder(null);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        Iuser.setBackground(new java.awt.Color(255, 198, 0));
        Iuser.setFont(new java.awt.Font("Roboto Light", 2, 16)); // NOI18N
        Iuser.setForeground(new java.awt.Color(153, 153, 153));
        Iuser.setText("Ingrese su nombre de usuario");
        Iuser.setBorder(null);
        Iuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IuserMousePressed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        Ipass.setBackground(new java.awt.Color(255, 198, 0));
        Ipass.setFont(new java.awt.Font("Roboto Light", 2, 16)); // NOI18N
        Ipass.setForeground(new java.awt.Color(153, 153, 153));
        Ipass.setText("***************");
        Ipass.setBorder(null);
        Ipass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IpassMousePressed(evt);
            }
        });

        javax.swing.GroupLayout PanelDoradoLayout = new javax.swing.GroupLayout(PanelDorado);
        PanelDorado.setLayout(PanelDoradoLayout);
        PanelDoradoLayout.setHorizontalGroup(
            PanelDoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDoradoLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addGroup(PanelDoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDoradoLayout.createSequentialGroup()
                        .addComponent(LAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDoradoLayout.createSequentialGroup()
                        .addComponent(Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
            .addGroup(PanelDoradoLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(PanelDoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextUser, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPass)
                    .addComponent(jSeparator1)
                    .addComponent(Iuser, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(Ipass))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelDoradoLayout.setVerticalGroup(
            PanelDoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDoradoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(LAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(TextUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(Iuser, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextPass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelDoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDoradoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Ipass, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDoradoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        bg.add(PanelDorado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 470, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IuserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IuserMousePressed
// Verificar si el texto es el texto de ejemplo
    if (Iuser.getText().equals("Ingrese su nombre de usuario")) {
        Iuser.setText("");
        Iuser.setForeground(Color.BLACK);
    }

    Ipass.setText("**************");
    Ipass.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_IuserMousePressed

    private void IpassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IpassMousePressed
        // Verificar si el texto es el texto de ejemplo
    if (new String(Ipass.getPassword()).equals("***************")) {
        Iuser.setText("Ingrese su nombre de usuario");
        Iuser.setForeground(new Color(153,153,153));
        Ipass.setText("");
        Ipass.setForeground(Color.BLACK);
    }
    }//GEN-LAST:event_IpassMousePressed

    
    private void EntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarMouseClicked
//Aqui se pone el codigo para entar 
        ProxyUsuario proxy = new ProxyUsuario();
        String usuario = Iuser.getText();
         char[] contraseniaChars = Ipass.getPassword();
        String contrasenia = new String(contraseniaChars);
        proxy.iniciarSesion(usuario, contrasenia);
        
        
        Dashboard db = new Dashboard();
        db.setVisible(true);
    }//GEN-LAST:event_EntrarMouseClicked
   
    
    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
//Aqui se pone la funcion de la pagina anterior de la flecha
    System.exit(0);
    }//GEN-LAST:event_backMouseClicked

    private void btnRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseClicked
    Register registro = new Register();
    // Mostrar la ventana Registro
    registro.setVisible(true);
    // Ocultar la ventana Login
    this.setVisible(false);
    }//GEN-LAST:event_btnRegistroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entrar;
    private javax.swing.JPasswordField Ipass;
    private javax.swing.JTextField Iuser;
    private javax.swing.JLabel LAzul;
    private javax.swing.JLabel LDorado;
    private javax.swing.JLabel LQAPT;
    private javax.swing.JLabel LVuelos_Hoteles;
    private javax.swing.JPanel PanelAzul;
    private javax.swing.JPanel PanelDorado;
    private javax.swing.JLabel TextPass;
    private javax.swing.JLabel TextUser;
    private javax.swing.JButton back;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
